nektos/act

README.md

again, thought this might be helpful for other users.
**Caveat**: I'm not an InfoSec expert, so someone should look this over.
Don't want to encourage people to do stupid things.

explain how to run act with secrets

---

actions/runner_exec.go
actions/runner_test.go
actions/testdata/env.workflow
common/git.go
common/git_test.go

closes #67 
---
~~If you think this is a good addition, I'll work into fixing/adding tests and making the code cleaner :)~~ done.
tested it locally, it works!

feat: support branches as GITHUB_REF

---

README.md

I've created an AUR package for act :)

add arch linux installation instructions

---

.github/actions/choco/Dockerfile
.github/actions/choco/action.yml
.github/actions/choco/entrypoint.sh
.github/workflows/push.yml
.gitignore
README.md
VERIFICATION
act-cli.nuspec
actcli.nuspec

Fix 132 - support for chocolatey install

---

pkg/runner/step_context.go

Use env variables in Action.Runs.Env

---

CONTRIBUTING.md

See [macOS](https://en.wikipedia.org/wiki/MacOS)

Update brand name for macOS

---

README.md

I added a Known Issues section in the readme file to document the issues that have been resolved so developers encountering those issues will find the solution quickly.

Added documentation for module not found issue.

---

pkg/common/git.go

Act switched from checking out a branch to checking out a hash in order to resolve #24 - see bc5c23e8e48ee1886ac274965852196d1ec3ba3f
This had a side effect of preventing `w.Pull()` from updating to the latest commit if a ref was a branch/tag and the repo already exists on disk.
This commit checks if input.Ref is equivalent to the resolved hash, and runs `r.Fetch()` and checks out the branch for `input.Ref` if it is different. `w.Pull()` can then pull the latest changes before we checkout `*hash` again like normal

Pull latest changes from ref using cached repo

---

README.md

https://github.com/nektos/act/blob/master/Makefile#L14

Update unit test command to `make test`

---

pkg/runner/run_context.go
pkg/runner/step_context.go

Properly pass format argument to avoid MISSING

---

pkg/model/workflow.go
pkg/runner/expression_test.go

1. Swaps comments on StepTypeUsesActionLocal, StepTypeUsesActionRemote
2. gofmt on pkg/runner/expression_test.go

Fixes comments on StepType enum consts

---

README.md
cmd/root.go

Hey 👋 thx for amazing work!
I needed to load secrets from a file and found the solution in issues, would be nice to add it to README :)
https://github.com/nektos/act/issues/279

Document `secret-file` in README and add example

---

README.md

Fixes https://github.com/nektos/act/issues/319

Added docker pull instructions for building from source

---

Makefile

Makefiles should declare non-file targets as PHONY
- https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
- https://unix.stackexchange.com/a/321947

Added PHONY targets to Makefile

---

cmd/input.go
cmd/root.go
pkg/container/docker_run.go
pkg/runner/run_context.go
pkg/runner/runner.go
pkg/runner/step_context.go

add privileged mode

---

pkg/runner/expression.go
pkg/runner/expression_test.go

feat: add fromJSON support

---

pkg/runner/runner_test.go

This will allow other tests to be created in runner_test.go that can
be tested individually.

Extract runTestJobFile from TestRunEvent

---

README.md

Warns that not Apple Silicon compatible.

---

README.md
cmd/platforms.go

Closes #444
(previous PR: #445)

Add Ubuntu 20.04 to supported platforms

---

pkg/runner/step_context.go

Use static initial PATH

---

cmd/input.go
cmd/root.go
pkg/runner/logger.go
pkg/runner/runner.go

Add option to disable hiding of secrets

---

pkg/container/docker_run.go

Fix slashes when running on Windows

---

cmd/secrets.go
pkg/runner/expression.go
pkg/runner/expression_test.go

Make all secrets case insensitive by formatting them to uppercase

---

README.md
pkg/runner/run_context.go

Update parts of repo

---

pkg/container/docker_run.go
pkg/model/workflow.go
pkg/runner/expression.go
pkg/runner/expression_test.go
pkg/runner/run_context.go
pkg/runner/step_context.go

Format sources with gofmt

---

README.md
cmd/input.go
cmd/root.go

Add option to detect event type from workflow, closes #484

Add autodetect event flag

---

pkg/runner/run_context.go
pkg/runner/run_context_test.go

Report error when `if` expression is invalid

---

cmd/root.go
go.mod
go.sum

Add survey during first run for a default image
@cplee Finally had a moment to draft that up, let me know how you see it

Add survey during first run for a default image

---

README.md
cmd/root.go

Closes #357 (somehow I completely forgot about that issue)

Load .secrets file as default

---

pkg/runner/step_context.go

I changed `uses:` directive syntax to the same behavior to the current GitHub Actions.
Closes #438
After this changes was merged, act started with the workflow having invalid uses directive will stop with an invalid syntax error, like:
```console
% new-act push
[Continuous integration/check] 🚀  Start image=catthehacker/ubuntu:act-latest
[Continuous integration/check]   🐳  docker run image=catthehacker/ubuntu:act-latest entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Continuous integration/check]   🐳  docker cp src=(snip) dst=/github/workspace
[Continuous integration/check] ⭐  Run actions/checkout@v2
[Continuous integration/check]   ✅  Success - actions/checkout@v2
[Continuous integration/check] ⭐  Run OskarStark/php-cs-fixer-ga
[Continuous integration/check]   ❌  Failure - …
```

Stop current execution if there is the invalid syntax in the workflow

---

pkg/runner/run_context.go

Print error when runs-on key is not defined

---

cmd/root.go

Hi,
Like what I posted at https://github.com/nektos/act/pull/483#issuecomment-769547060
I made a pr for that, how do you think it?
@cplee @catthehacker

fix: --version, --help do not need check platform config

---

pkg/runner/expression.go
pkg/runner/step_context.go

Interpolate `with:` inputs

---

README.md
cmd/root.go

`README.md`:
- Minor formatting fixes
- Added more instructions/explanations
`cmd/root.go`:
- Based on recent conversations on [nektos/act on Gitter](https://gitter.im/nektos/act), adding notice about `large` image and link to repository for `.actrc` reference
Seems like people discover `act` and don't read README
possible improvements for future:
- provide `help` subcommand that will include what `README.md` has
- ???

Update `README.md`/`cmd/root.go` with additional information

---

pkg/runner/expression.go
pkg/runner/expression_test.go

Closes #496
Notes:
*strings.Builder.WriteRune* and others describes:
> It returns the length of r and a nil error.
So I added `//nolint` comment to each statement.

Shouldn't rewrite dot in a string to index syntax

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_template.md
.github/ISSUE_TEMPLATE/issue_template.md

This should help get us a bit more well-formatted issues and get minimum required info
<details>
<summary>Issues</summary>
</details>
<details>
<summary>Creating new issue</summary>
</details>

Add GitHub issue templates

---

pkg/model/workflow.go

fixes #528
Co-authored-by: Hugh Lunt <hugh.lunt@itv.com>

Removed pipefail from bash shell execution to match GitHub Actions

---

pkg/common/cartesian_test.go

Fix indent with gofmt

---

README.md

* fix link to issue #97 in README.md explaining why certain runner platforms are not supported

Fix link to issue #97 in README.md

---

README.md
cmd/platforms.go
cmd/root.go
pkg/runner/runner_test.go
pkg/runner/step_context_test.go
pkg/runner/testdata/actions/docker-local/Dockerfile
pkg/runner/testdata/actions/docker-url/action.yml
pkg/runner/testdata/basic/push.yml
pkg/runner/testdata/fail/push.yml
pkg/runner/testdata/job-container/push.yml
pkg/runner/testdata/uses-docker-url/push.yml

Updates all images to their latest releases

Update Docker images

---

pkg/runner/run_context.go

#534 feat: step continues when continue-on-error is ture

---

pkg/runner/run_context.go

Adds `ImageOS` variable that certain actions are using to determine OS and it's version

Add `ImageOS` env var based on running platform

---

pkg/model/workflow.go

Invoke login shells to source `/etc/environment`

---

README.md
cmd/root.go

GitHub Actions switched `ubuntu-latest` to `ubuntu-20.04`
Ref:
https://github.com/actions/virtual-environments/issues/1816
https://github.com/actions/virtual-environments/pull/2852

fix: update `ubuntu-latest` to point to `ubuntu-20.04`

---

cmd/root.go

Currently when running `act` and `.actrc` doesn't exists as well as no `--platform` was specified, chosen default image for platforms will be ignored and `act` will run with default ones defined in https://github.com/nektos/act/blob/41b03b581c7aec251d96e9a5ea27009542a798d4/cmd/platforms.go#L9-L12

Fix platforms during initial setup

---

pkg/model/workflow.go
pkg/runner/runner_test.go
pkg/runner/step_context.go
pkg/runner/testdata/powershell/push.yml

Code: https://github.com/actions/runner/blob/main/src/Runner.Worker/Handlers/ScriptHandlerHelpers.cs
Docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
Fixes #467
Replaces #466
Thanks to @catthehacker for the direction

Update Shell Tasks to match ScriptHandlerHelpers

---

pkg/model/planner.go
pkg/model/planner_test.go
pkg/model/testdata/invalid-job-name/push.yml

Fail workflow if the job name is invalid

---

README.md

👋 @nektos, @catthehacker,
I've spent a bit of time to help people find and compare self-hosted GitHub Action solutions and compiled a curated collection called [awesome-runners](https://github.com/jonico/awesome-actions).
I am using nektos/act for quite some while now and while your project is not a self-hosted action runner solution itself, it is a ✨ tool to test the images and workflows for self-hosted runners before they are rolled out at large scale to its end users - so I [recommended and linked to your your project from the testing section](https://github.com/jonico/awesome-runners/blob/main/README.md#a-word-about-self-hosted-action-runner-images--virtual-environments-and-how-to-test-locally).
[Here](https://github.com/jonico/visualize-actions-matrix-builds-on-k8s/blob/master/simulat …

Add nektos/act to awesome-runner list

---

.github/workflows/push.yml

Reworked macOS install and it's much faster (test seems to be faster as well now)
Added Go module caching
Fixes #641

feat: Speeding up workflows

---

pkg/runner/run_context.go
pkg/runner/runner_test.go
pkg/runner/testdata/issue-597/spelling.yaml

Fixes #597 
Due to the order of events, the stepenv was evaluated before the if statement was checked. This fix changes the order of events aswell as tests to test this. Inspiration of the test was taken from #597. 
As I understand the code, I think this solution fixes it.

Fixes Issue #597

---

README.md

feat: add `go` install instruction

Add install instructions for `go`

---

README.md

fix: remove Windows issue from `README.md`

---

README.md
cmd/input.go
cmd/root.go
pkg/runner/run_context.go
pkg/runner/runner.go

feat: add option for custom socket path

---

pkg/container/docker_run.go
pkg/runner/run_context.go
pkg/runner/run_context_test.go
pkg/runner/step_context.go

feat: add option to specify user for exec
fix: move actions to static path outside workdir
Issues:
Fixes #669 
Fixes https://github.com/catthehacker/docker_images/issues/9

Move actions path outside of workdir

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_template.md
.github/linters/.markdown-lint.yml
.markdownlint.yml

add additional information to be provided by user that should help in troubleshooting

fix: update issue template

---

pkg/runner/logger.go

fix: don't replace empty secrets

---

.github/workflows/checks.yml

Codecov should be working properly now
https://github.com/codecov/codecov-action/releases/tag/v1.5.2

fix: update codecov action (again)

---

README.md

Adds instructions for installation via [MacPorts](https://www.macports.org).

README: add MacPorts info

---

pkg/runner/step_context.go

fixes https://github.com/nektos/act/issues/754
this will prevent actions from failing that use resources outside
of the action directory
Doesn't have test because all actions for https://github.com/microsoft/powerplatform-actions require authentication

fix: copy whole action dir to container

---

cmd/list.go
pkg/model/planner.go
pkg/model/workflow.go

Improve `--list`

---

go.mod
go.sum
pkg/container/docker_run.go
pkg/runner/run_context.go
pkg/runner/runner_test.go
pkg/runner/testdata/container-hostname/push.yml

support for container option: --hostname

---

pkg/runner/run_context.go

Provide hint for -P

---

.github/workflows/checks.yml
.github/workflows/release.yml

It seems v0.180.0 panics on Homebrew section

ci: pin goreleaser version

---

.gitignore
pkg/runner/step_context.go

refactor: re-implement `embed` without "unused" import

---

pkg/runner/step_context.go
pkg/runner/testdata/actions/docker-local/action.yml
pkg/runner/testdata/actions/docker-local/entrypoint.sh
pkg/runner/testdata/local-action-dockerfile/push.yml

fix: interpolate env for step actions

---

pkg/model/action.go
pkg/runner/step_context.go
pkg/runner/testdata/actions/docker-url/action.yml

fix: correctly unmarshal entrypoint

---

README.md

For folks who need latest fixes or "live on the edge"

docs: add brew installation from HEAD

---

pkg/runner/run_context.go
pkg/runner/runner_test.go
pkg/runner/step_context.go
pkg/runner/testdata/outputs/push.yml

All credits go to @ChristopherHX which fixed this issue (https://github.com/ChristopherHX/act/commit/fd9f40cdc02dc72c40a9c33450d638d6e8e8ee57).
I only created a PR for this so it will be fixed in the upstream binary.
This fixes #758

Don't interpolate joboutputs, before job is done

---

.github/actions/choco/Dockerfile
.github/actions/choco/entrypoint.sh

ci(choco): fix chocolatey docker build

---

.editorconfig
.github/actions/choco/Dockerfile
.github/actions/choco/action.yml
.github/actions/choco/entrypoint.sh
.github/workflows/checks.yml
.github/workflows/release.yml

- Fix typo in `.editorconfig` + add formatting for all files
- Fix chocolatey installation according to official instruction
- Add test for choco action

Fix and test choco action

---

pkg/runner/runner_test.go
pkg/runner/testdata/if-env-act/push.yml

This feature of act needs a Test, since it broke recently.
Resolves https://github.com/nektos/act/issues/940

Test: env.ACT in if condition of the workflow

---

cmd/secrets.go

fixes https://github.com/nektos/act/issues/979

fix: print line after password prompt

---

cmd/root.go

fix: trim whitespace from actrc

---

pkg/exprparser/functions.go
pkg/exprparser/functions_test.go

You can test this with https://github.com/ChristopherHX/runner.server against actions/runner or online
```yaml
on: push
jobs:
testf:
if: tojson(fromjson('[null]')[0]) == 'null'
steps:
- run: echo ${{github.workspace}}
```
I expect this job to be executed

Fix: tojson(null) == 'null'

---

pkg/model/testdata/container-volumes/push.yml
pkg/model/workflow_test.go
pkg/runner/run_context.go
pkg/runner/run_context_test.go
pkg/runner/runner_test.go

It was assumed that 'workflow.yml' was parsed and validated correctly in advance.

implement volume mount for container job

---

pkg/runner/run_context.go

I have a lot of stale act-....-env volumes
_I have the feeling, this can cause bugs if we have a job id collisions_

Remove the correct Volume

---

pkg/runner/action.go
pkg/runner/action_composite.go
pkg/runner/runner_test.go
pkg/runner/step.go
pkg/runner/step_action_local.go
pkg/runner/step_action_local_test.go
pkg/runner/step_action_remote.go
pkg/runner/step_action_remote_test.go
pkg/runner/testdata/uses-action-with-pre-and-post-step/last-action/action.yml
pkg/runner/testdata/uses-action-with-pre-and-post-step/last-action/post.js
pkg/runner/testdata/uses-action-with-pre-and-post-step/push.yml

This PR does implement the pre-action step for remote actions.

feat: implement pre-action step

---

README.md

Helps notify others that services are not currently supported https://github.com/nektos/act/issues/173

Update docs to reflect status of support for services

---

README.md

Added documentation on how to pass inputs for workflows that require them in the README file to have better visibility.
Fixes #1237

Improve docs for events inputs

---

pkg/runner/runner.go
pkg/runner/runner_test.go
pkg/runner/testdata/evalenv/push.yml

This fixes #1221 for me, but I'm not sure that it does not break anything else.
With the test from #1221, I get the proper output:
```
[test.yml/interp] ⭐ Run Main Dump environment
[test.yml/interp]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
| V1: VALUE1
| V1_V2: VALUE1_VALUE2
| x_V1: x_VALUE1
| x_V1_V2: x_VALUE1_VALUE2
[test.yml/interp]   ✅  Success - Main Dump environment
[test.yml/interp] ⭐ Run Main Interpolate in script
[test.yml/interp]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=
| env.V1: VALUE1
| env.V1_V2: VALUE1_VALUE2
| env.x_V1: x_VALUE1
| env.x_V1_V2: x_VALUE1_VALUE2
[test.yml/interp]   ✅  Success - Main Interpolate in script
[test.yml/interp] ⭐ Run Main …
```

Made env interpolated instead of evaluated.

---

README.md

[ArchWiki/SystemMaintenance](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported)

Arch best practice is to not run partial upgrades

---

.github/actions/run-tests/action.yml
.github/workflows/checks.yml

Examples
- https://github.com/nektos/act/actions/runs/3988464133/attempts/1#summary-10827280870
- https://github.com/nektos/act/actions/runs/3989524486/attempts/1#summary-10830484825
Logs of each tests are uploaded additionally as an artifact
Closes https://github.com/nektos/act/issues/1567

feat: step summary of test results

---

README.md

docs: remove help section

---

pkg/model/workflow.go
pkg/runner/testdata/.github/workflows/local-reusable-workflow-no-inputs-array.yml
pkg/runner/testdata/.github/workflows/local-reusable-workflow-no-inputs-string.yml
pkg/runner/testdata/uses-workflow/local-workflow.yml

fix: reusable workflow panic

---

.github/workflows/checks.yml
.goreleaser.yml

Add riscv64 binary release

---

cmd/root.go
cmd/root_test.go
cmd/testdata/secrets.yml

* do ToUpper for keys not only for cli args
* add tests
* Working on fixing the missing coverage of the cmd package by adding tests

fix: secret file reading

---

cmd/root.go

A peer didn't understand the behavior/way to get the other behavior. I think this clarifies things...

Clarify --no-skip-checkout flag

---

cmd/root.go

Refer to nektosact.com

---

cmd/input.go
cmd/root.go
pkg/runner/runner.go
pkg/runner/runner_test.go

feat: Add an option to set act executor concurrency by environment variable.

---

pkg/schema/workflow_schema.json

Otherwise act would reject such workflows right away

feat: allow workflow description

---

pkg/model/action.go
pkg/runner/action.go

* CI is broken right now due to hello world action upgrade

refactor: simplify adding new node versions add node 24
